apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: es-data
  name: es-data
  namespace: signal-suite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
