apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-claim3
  namespace: signal-suite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
