apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub
  namespace: signal-suite
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: jupyterhub
