apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-suite
  namespace: signal-suite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-suite
  template:
    metadata:
      labels:
        app: signal-suite
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              value: local
          image: localhost:6000/signal-suite
          name: signal-suite
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/logs
              name: signal-suite-logs
            - mountPath: /app/data
              name: signal-suite-data
      restartPolicy: Always
      volumes:
        - name: signal-suite-logs
          persistentVolumeClaim:
            claimName: signal-suite-claim-logs
        - name: signal-suite-data
          persistentVolumeClaim:
            claimName: signal-suite-claim-data
