apiVersion: v1
kind: Service
metadata:
  labels:
    app: signal-suite
  name: signal-suite
  namespace: signal-suite
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: signal-suite
